### ISSUE TITLE
Could NOT find Python3

### ISSUE THREAD

**Issue by noahchalifour** [llvm/torch-mlir#647] opened 2022-03-08 20:26 UTC
I am trying to build the python packages using the commands provided in the readme. I get an error when running: 

```
cmake -GNinja -Bbuild \
  -DCMAKE_C_COMPILER=clang \
  -DCMAKE_CXX_COMPILER=clang++ \
  -DPython3_FIND_VIRTUALENV=ONLY \
  -DLLVM_ENABLE_PROJECTS=mlir \
  -DLLVM_EXTERNAL_PROJECTS="torch-mlir;torch-mlir-dialects" \
  -DLLVM_EXTERNAL_TORCH_MLIR_SOURCE_DIR=`pwd` \
  -DLLVM_EXTERNAL_TORCH_MLIR_DIALECTS_SOURCE_DIR=`pwd`/external/llvm-external-projects/torch-mlir-dialects \
  -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
  -DLLVM_TARGETS_TO_BUILD=host \
  external/llvm-project/llvm
```

I have also tried running the above command and adding `-DPython3_EXECUTABLE="$(which python)"`, however I get the same error.

I don't know if the fact that I'm on an M1 MacBook is an issue, any help would be appreciated.

Here is the error:

```
-- Performing Test C_SUPPORTS_MISLEADING_INDENTATION_FLAG - Success
-- Performing Test CXX_SUPPORTS_MISLEADING_INDENTATION_FLAG
-- Performing Test CXX_SUPPORTS_MISLEADING_INDENTATION_FLAG - Success
-- Performing Test LINKER_SUPPORTS_COLOR_DIAGNOSTICS
-- Performing Test LINKER_SUPPORTS_COLOR_DIAGNOSTICS - Failed
-- Looking for os_signpost_interval_begin
-- Looking for os_signpost_interval_begin - found
-- Performing Test macos_signposts_usable
-- Performing Test macos_signposts_usable - Success
-- Found Python3: /Users/noahchalifour/Code/noahchalifour/AI_TEXT_EDITOR_4250/ai-src/torch-mlir/mlir_venv/bin/python (found suitable version "3.8.9", minimum required is "3.6") found components: Interpreter 
-- Linker detection: ld64
-- Performing Test HAS_WERROR_GLOBAL_CTORS
-- Performing Test HAS_WERROR_GLOBAL_CTORS - Success
-- Performing Test LLVM_HAS_NOGLOBAL_CTOR_MUTEX
-- Performing Test LLVM_HAS_NOGLOBAL_CTOR_MUTEX - Failed
-- Found Git: /usr/bin/git (found version "2.32.0 (Apple Git-132)") 
-- Targeting AArch64
-- Performing Test C_SUPPORTS_WERROR_IMPLICIT_FUNCTION_DECLARATION
-- Performing Test C_SUPPORTS_WERROR_IMPLICIT_FUNCTION_DECLARATION - Success
-- Performing Test C_SUPPORTS_WERROR_MISMATCHED_TAGS
-- Performing Test C_SUPPORTS_WERROR_MISMATCHED_TAGS - Success
-- Could NOT find Python3 (missing: Development Development.Module Development.Embed) (found suitable version "3.9", minimum required is "3.6")
CMake Error at /opt/homebrew/Cellar/cmake/3.22.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Python3 (missing: Development.Module NumPy) (found suitable
  version "3.8.9", minimum required is "3.6")
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.22.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.22.3/share/cmake/Modules/FindPython/Support.cmake:3166 (find_package_handle_standard_args)
  /opt/homebrew/Cellar/cmake/3.22.3/share/cmake/Modules/FindPython3.cmake:490 (include)
  /Users/noahchalifour/Code/noahchalifour/AI_TEXT_EDITOR_4250/ai-src/torch-mlir/external/llvm-project/mlir/cmake/modules/MLIRDetectPythonEnv.cmake:33 (find_package)
  /Users/noahchalifour/Code/noahchalifour/AI_TEXT_EDITOR_4250/ai-src/torch-mlir/external/llvm-project/mlir/CMakeLists.txt:135 (mlir_configure_python_dev_packages)
```

**Comment by stephenneuendorffer** [comment] 2022-03-08 21:01
I believe you need to get numpy installed: `pip3 install numpy`.  the CMAKE python support is... finicky.

**Comment by noahchalifour** [comment] 2022-03-08 21:05
@stephenneuendorffer I can confirm that numpy is installed.

```
> pip3 list                      
Package           Version
----------------- ------------------
numpy             1.22.3
Pillow            9.0.1
pip               22.0.4
pybind11          2.9.1
setuptools        49.2.1
torch             1.12.0.dev20220308
torchvision       0.11.3
typing_extensions 4.1.1
wheel             0.37.1
```

**Comment by cathyzhyi** [comment] 2022-03-08 21:24
Are you using virtual environment like conda? When python is in conda environment I needed to add this patch to make cmake work with python.
```
diff --git a/mlir/cmake/modules/MLIRDetectPythonEnv.cmake b/mlir/cmake/modules/MLIRDetectPythonEnv.cmake
index 87039fd4b2e9..9fdbf909039e 100644
--- a/mlir/cmake/modules/MLIRDetectPythonEnv.cmake
+++ b/mlir/cmake/modules/MLIRDetectPythonEnv.cmake
@@ -30,12 +30,16 @@ macro(mlir_configure_python_dev_packages)
       COMPONENTS Development)
     set(_python_development_component Development.Module)
   endif()
-  find_package(Python3 ${LLVM_MINIMUM_PYTHON_VERSION}
-    COMPONENTS Interpreter ${_python_development_component} NumPy REQUIRED)
+  # find_package(Python3 ${LLVM_MINIMUM_PYTHON_VERSION}
+  #   COMPONENTS Interpreter ${_python_development_component} NumPy REQUIRED)
+  set(Python3_ROOT_DIR "python_path")
+  find_package(Python3 3.9.7 EXACT COMPONENTS Interpreter Development REQUIRED)
```

**Comment by noahchalifour** [comment] 2022-03-08 22:54
@cathyzhyi That worked, thanks!

**Comment by Vigilans** [comment] 2022-03-10 11:36
> find_package(Python3 ${LLVM_MINIMUM_PYTHON_VERSION}
>    COMPONENTS Interpreter ${_python_development_component} NumPy REQUIRED)

Seems for conda environment, simply replacing `${_python_development_component}` with `Development` fixes the problem.

**Comment by silvasean** [comment] 2022-03-10 15:51
Can we dig into this? I don't like us "fixing" a bug by having people carry around private build patches. It looks like we already have some logic to choose `_python_development_component` -- is there something additional we can do here to detect Conda or whetever the underlying issue is and go with "Development"  instead of "Development.Module"?

@stephenneuendorffer any thoughts on the root cause here this? It looks like some of the existing logic comes from https://reviews.llvm.org/D118148

**Comment by mikeurbach** [comment] 2022-03-10 17:49
Not sure if this is related, but we were seeing some issues with Python3_EXECUTABLE on windows after D118148, and John appears to have found a fix in: https://github.com/llvm/llvm-project/commit/cb318526b0417b1a03255ee79920ad613b0ae691

**Comment by noahchalifour** [comment] 2022-03-10 22:59
I ended up deleting my build and re-building with `build_tools/build_python_wheels.sh` without the modification to the CMake file and it worked

**Comment by stellaraccident** [comment] 2022-03-11 04:28
> My thought is that "Development.Module" is just broken and we should use "Development" everywhere. The focus on Development.Module is intended to support a manylinux environment. @stellaraccident Can we excise this mess and just tell those using manylinux to install the additional packages needed to satisfy "Development"?

Unfortunately, it is worse than that: Development.Module is necessary to build on any non shared lib python install, which covers a lot. The people who hit this path don't have packages they can install to fix it. 

But I agree it is broken. I have been trying to get a repro and even went to the trouble to build a docker image exactly like the last problem report and did not repro. I am fairly certain that with a failure repro, I could find/fix this, but it is stubbornly refusing to break for me :(

Perhaps a better stopgap is to have a cmake flag to enable Development.Module mode and otherwise use Development. That way, the people/systems in the minority have *an* option, even if not the default.

**Comment by stellaraccident** [comment] 2022-03-11 04:30
I kind of want to kill all of the auto detect goo and just run a little python script to probe and set the right options. It is just not that hard, and this situation is kind of ridiculous.

**Comment by stellaraccident** [comment] 2022-03-11 04:40
So, I had wanted to do this properly -- repro, file a bug report, fix cmake. But how about this: I just script out what we need in the simplest way (I've written this before and it is all of like 15 lines of code). We put that behind a flag to let people try it for a bit, failing back to just pushing for Development. If my new things works, we do the flag and get off of this crazy ride.

I can do that tomorrow.

**Comment by stephenneuendorffer** [comment] 2022-03-11 04:46
No severe objections, but If OP says it's not a bug, then I suggest we leave it be for the moment.  In my build environment there at least 3 other cmake projects that are trying to find python stuff through cmake... at least at the moment they are consistently working or broken :)  I hesitate to add yet another mechanism.

**Comment by stellaraccident** [comment] 2022-03-11 05:06
I think there is enough evidence to say that a significant fraction of people are at least experiencing flakiness. Also see the commentary here: https://reviews.llvm.org/D118148

**Comment by stellaraccident** [comment] 2022-03-11 05:07
Let me give it a shot and see how it turns out. I think this is actually a fairly pervasive, if not intermittent, issue.

**Comment by Vigilans** [comment] 2022-03-11 14:46
FYI, [`google/iree`]  deals with it in this way:
https://github.com/google/iree/blob/c96372348654eea8548509d38df5c8e8b179aef3/CMakeLists.txt#L275-L280
```cmake
    # Configuring the Development.Module is flaky in multi-project setups.
    # "Bootstrapping" by first looking for the optional Development component
    # seems to be robust generally.
    # See: https://reviews.llvm.org/D118148
    find_package(Python3 COMPONENTS Interpreter Development)
    find_package(Python3 COMPONENTS Interpreter Development.Module REQUIRED)
```

**Comment by dragonware-com** [comment] 2022-05-01 18:06
Just tried on Ubuntu 20.04, and the problem still exists:
```
-- Performing Test C_SUPPORTS_WERROR_MISMATCHED_TAGS - Failed
-- Could NOT find Python3 (missing: Python3_INCLUDE_DIRS Development Development.Module Development.Embed) (found suitable version "3.8.10", minimum required is "3.6")
CMake Error at /home/welson/git/torch-mlir/mlir_venv/lib/python3.8/site-packages/cmake/data/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Python3 (missing: Python3_INCLUDE_DIRS Development.Module
  NumPy) (found suitable version "3.8.10", minimum required is "3.6")
```

**Comment by powderluv** [comment] 2022-05-01 20:07
on 20.04 do you have the python3.8-dev package installed ?

**Comment by dragonware-com** [comment] 2022-05-01 20:22
> on 20.04 do you have the python3.8-dev package installed ?

Oh wow, that actually worked! Thanks for the help! I guess that should be listed in the build doc.

**Comment by silvasean** [comment] 2022-05-02 12:50
Just added it.

**Comment by silvasean** [comment] 2022-10-07 14:21
We have changed a lot about our build configurations. Let's close this for now. Please file a new bug if you have an issue with the current setup.

**Closed by silvasean** 2022-10-07 14:21 UTC
