### ISSUE TITLE
error: number of 'torch.slot's in a 'torch.nn_module' must match number of 'torch.attr's in the corresponding 'torch.class_type'

### ISSUE THREAD

**Issue by noahchalifour** [llvm/torch-mlir#656] opened 2022-03-10 22:53 UTC
Hi, I am new to torch-mlir and I'm trying to use it to optimize the inference time for my model on my M1 MacBook. I am trying to use the GPT-Neo model from the Transformers Python package alongside [SHARK](https://github.com/NodLabs/SHARK) to be able to run the model faster on my M1 chip. When running the inference I get the following error:

```
error: number of 'torch.slot's in a 'torch.nn_module' must match number of 'torch.attr's in the corresponding 'torch.class_type'
note: see current operation: %11 = "torch.nn_module"() ({
^bb0:
}) : () -> !torch.nn.Module<"__torch__.transformers.models.gpt_neo.modeling_gpt_neo.GPTNeoSelfAttention">
Traceback (most recent call last):
  File "/Users/noahchalifour/Code/noahchalifour/AI_TEXT_EDITOR_4250/ai-src/model_server.py", line 109, in <module>
    print(shark_inference(
  File "/Users/noahchalifour/Code/noahchalifour/AI_TEXT_EDITOR_4250/ai-src/shark_runner.py", line 98, in shark_inference
    pm.run(mb.module)
RuntimeError: Failure while executing pass pipeline.
```

I'm not sure what the first line means but it seams to have something to do with GPTNeoSelfAttention.

Here is the code I'm using:

```
import torch
from torch_mlir.dialects.torch.importer.jit_ir import ClassAnnotator, ModuleBuilder

from torch_mlir.passmanager import PassManager
from iree import runtime as ireert
import iree.compiler as ireec
import numpy as np
import os

from transformers import GPTNeoForCausalLM, AutoTokenizer
import torch

class NEO(torch.nn.Module):
    def __init__(self, model_name):
        super().__init__()

        model = GPTNeoForCausalLM.from_pretrained(model_name,
            torchscript=True).eval()

        random_tokens = torch.randint(10000, (5,))
        self.traced_model = torch.jit.trace(model, random_tokens)
    
    def forward(self, x):
        sentence = x
        predictions, _ = self.traced_model(sentence)
        token = torch.argmax(predictions[-1, :], dim=0, keepdim=True)
        sentence = torch.cat((sentence, token), 0)
        return sentence

def shark_inference(module, input, device="cpu", dynamic=False, jit_trace=False):

    if jit_trace:
        module = getTracedRecursiveScriptModule(module, input, dynamic)
        module = get_serialized_test(module)
    else:
        module = torch.jit.script(module)

    input_shape = list(input.shape)
    if dynamic:
        input_shape = [-1 for i in range(len(input.shape))]

    mb = ModuleBuilder()
    class_annotator = ClassAnnotator()
    iree_device = {"cpu": "dylib", "gpu": "cuda", "vulkan": "vulkan"}
    class_annotator.exportNone(module._c._type())
    class_annotator.exportPath(module._c._type(), ["forward"])
    class_annotator.annotateArgs(
        module._c._type(),
        ["forward"],
        [
            None,
            (input_shape, input.dtype, True),
        ],
    )
    mb.import_module(module._c, class_annotator)

    with mb.module.context:
        pm = PassManager.parse(
            "torchscript-module-to-torch-backend-pipeline,torch-backend-to-linalg-on-tensors-backend-pipeline"
        )
        pm.run(mb.module)

    flatbuffer_blob = ireec.compile_str(
        str(mb.module), target_backends=[iree_device[device]]
    )
    vm_module = ireert.VmModule.from_flatbuffer(flatbuffer_blob)
    tracer = ireert.Tracer(os.getcwd())
    config = ireert.Config(iree_device[device], tracer)
    ctx = ireert.SystemContext(config=config)
    ctx.add_vm_module(vm_module)
    ModuleCompiled = ctx.modules.module["forward"]
    result = ModuleCompiled(input.numpy())
    result_numpy = np.asarray(result, dtype=np.float32)
    result_copy = np.copy(result_numpy)
    return result_copy

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = NEO(MODEL_NAME)

prompt = 'The oceans are'

input_ids = tokenizer(prompt, return_tensors="pt").input_ids[0]

print(shark_inference(
    model,
    input_ids,
    device='cpu',
    dynamic=False,
    jit_trace=False))
```

Any help would be appreciated.

**Comment by silvasean** [comment] 2022-03-10 23:27
can you paste the full imported (invalid) IR?

**Comment by noahchalifour** [comment] 2022-03-10 23:31
@silvasean Sorry I'm new to this, what is the IR?

**Comment by silvasean** [comment] 2022-03-10 23:34
the compiler intermediate representation (in the form of a .mlir file)

**Comment by noahchalifour** [comment] 2022-03-10 23:56
Do you know where I could probably find that? Sorry this is my first time using torch-mlir.

Here is the output of `torch.jit.trace(NEO(MODEL_NAME), torch.randint(100, (5,)))`:

```
graph(%self.1 : __torch__.NEO,
      %x.1 : Tensor):
  %17 : bool = prim::Constant[value=1]() # /Users/noahchalifour/Code/noahchalifour/AI_TEXT_EDITOR_4250/ai-src/model_server.py:42:0
  %14 : int = prim::Constant[value=1]()
  %10 : int = prim::Constant[value=0]() # /Users/noahchalifour/Code/noahchalifour/AI_TEXT_EDITOR_4250/ai-src/model_server.py:42:0
  %11 : int = prim::Constant[value=-1]() # /Users/noahchalifour/Code/noahchalifour/AI_TEXT_EDITOR_4250/ai-src/model_server.py:42:0
  %13 : int = prim::Constant[value=9223372036854775807]() # /Users/noahchalifour/Code/noahchalifour/AI_TEXT_EDITOR_4250/ai-src/model_server.py:42:0
  %traced_model.1 : __torch__.transformers.models.gpt_neo.modeling_gpt_neo.GPTNeoForCausalLM = prim::GetAttr[name="traced_model"](%self.1)
  %6 : (Tensor, ((Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor))) = prim::CallMethod[name="forward"](%traced_model.1, %x.1) # :0:0
  %predictions.1 : Tensor, %8 : ((Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor), (Tensor, Tensor)) = prim::TupleUnpack(%6)
  %12 : Tensor = aten::select(%predictions.1, %10, %11) # /Users/noahchalifour/Code/noahchalifour/AI_TEXT_EDITOR_4250/ai-src/model_server.py:42:0
  %15 : Tensor = aten::slice(%12, %10, %10, %13, %14) # /Users/noahchalifour/Code/noahchalifour/AI_TEXT_EDITOR_4250/ai-src/model_server.py:42:0
  %token.1 : Tensor = aten::argmax(%15, %10, %17) # /Users/noahchalifour/Code/noahchalifour/AI_TEXT_EDITOR_4250/ai-src/model_server.py:42:0
  %21 : Tensor[] = prim::ListConstruct(%x.1, %token.1)
  %23 : Tensor = aten::cat(%21, %10) # /Users/noahchalifour/Code/noahchalifour/AI_TEXT_EDITOR_4250/ai-src/model_server.py:43:0
  return (%23)
```

Is that what you're looking for?

**Comment by silvasean** [comment] 2022-03-11 00:20
In this case, what I'm looking for is printing out `mb.module` right after the `mb.import_module` call.

**Comment by noahchalifour** [comment] 2022-03-11 00:39
So it actually seems that the error is coming from `mb.import_module`, I removed a try-catch that I had forgotten about and I get this really long error:

```
Traceback (most recent call last):
  File "/Users/noahchalifour/Code/noahchalifour/AI_TEXT_EDITOR_4250/ai-src/model_server.py", line 115, in <module>
    print(shark_inference(
  File "/Users/noahchalifour/Code/noahchalifour/AI_TEXT_EDITOR_4250/ai-src/shark_runner.py", line 88, in shark_inference
    mb.import_module(module._c, class_annotator)
ValueError: Unsupported import tensor type: (1,1,.,.) =
 Columns 1 to 26  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  1  1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  1  1  1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  1  1  1  1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0  0  0  0  0  0
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0  0  0  0  0
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0  0  0  0
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0  0  0
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0  0
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
.
.
.
  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0
  1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0
  1  1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0
  1  1  1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0
  1  1  1  1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0
  1  1  1  1  1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0  0  0  0  0  0
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0  0  0  0  0
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0  0  0  0
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0  0  0
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0  0
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[ CPUByteType{1,1,2048,2048} ]
```

**Comment by silvasean** [comment] 2022-03-22 18:37
Seems like a failure in [this function](https://github.com/llvm/torch-mlir/blob/7c3ba25238ac73850fcdd698be1fb084f8a58e49/python/torch_mlir/dialects/torch/importer/jit_ir/csrc/torch_to_mlir_utils.cpp#L250) - can you debug it?

**Comment by silvasean** [comment] 2022-03-22 18:38
I suspect it is an issue with the scalar type in this switch: https://github.com/llvm/torch-mlir/blob/7c3ba25238ac73850fcdd698be1fb084f8a58e49/python/torch_mlir/dialects/torch/importer/jit_ir/csrc/torch_to_mlir_utils.cpp#L314

**Comment by silvasean** [comment] 2022-03-22 18:39
You should be able to test it in this test with a torch.uint8 dtype: https://github.com/llvm/torch-mlir/blob/7c3ba25238ac73850fcdd698be1fb084f8a58e49/test/python/importer/jit_ir/ivalue_import/tensors.py#L19

**Comment by silvasean** [comment] 2022-10-07 14:20
We recently added torch.uint8 support, which appears to be the root cause. Closing this.

**Closed by silvasean** 2022-10-07 14:20 UTC
