### ISSUE TITLE
Update version pin to onnx 1.16

### ISSUE THREAD

**Issue by stellaraccident** [llvm/torch-mlir#3310] opened 2024-05-09 16:01 UTC
onnx 1.16 includes support for Python 3.12. We should upgrade. Based on a user report, there may need to be some cleanup.

**Comment by zjgarvey** [comment] 2024-05-09 17:26
Just to verify, you would like me to

1. pin onnx==1.16.0 in test-requirements.txt
2. check for e2e test regressions with config onnx and fix them
3. setup building nightly python wheels for python version 3.12
4. anything else?

**Comment by stellaraccident** [comment] 2024-05-09 17:32
That's it.

**Comment by zjgarvey** [comment] 2024-05-09 17:35
Sounds good. Thanks.

**Comment by zjgarvey** [comment] 2024-07-03 00:07
Closing since we updated to 1.16.1.

**Closed by zjgarvey** 2024-07-03 00:07 UTC
