### ISSUE TITLE
[LTC] Tests failing for the latest PyTorch release 2022-12-11

### ISSUE THREAD

**Issue by vivekkhandelwal1** [llvm/torch-mlir#1708] opened 2022-12-12 07:07 UTC
Hi, about 30 tests are failing for LTC with the latest Pytorch release (https://github.com/llvm/torch-mlir/pull/1703) version 2022-12-11. The error is similar for all the tests and is given below:
```
    FAIL - "Conv2dNoPaddingModule_basic"
        Runtime error: Traceback (most recent call last):
          File "/home/vivek/work/02_07/vivekkhandelwal1-torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/framework.py", line 302, in compile_and_run_test
            trace = config.run(compiled, golden_trace)
          File "/home/vivek/work/02_07/vivekkhandelwal1-torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/configs/lazy_tensor_core.py", line 35, in run
            cpu_outputs = tree_map(to_device('cpu'), output)
          File "/home/vivek/work/02_07/mlir_venv/lib/python3.8/site-packages/torch/utils/_pytree.py", line 195, in tree_map
            return tree_unflatten([fn(i) for i in flat_args], spec)
          File "/home/vivek/work/02_07/mlir_venv/lib/python3.8/site-packages/torch/utils/_pytree.py", line 195, in <listcomp>
            return tree_unflatten([fn(i) for i in flat_args], spec)
          File "/home/vivek/work/02_07/vivekkhandelwal1-torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/configs/lazy_tensor_core.py", line 15, in <lambda>
            return lambda e: e.to(device) if isinstance(e, torch.Tensor) else e
        RuntimeError: vector::_M_range_check: __n (which is 2) >= this->size() (which is 2)
```
The list of the failing tests is: https://github.com/llvm/torch-mlir/blob/1715371fe2e3030dcdddaee5597ce43aa620719c/e2e_testing/xfail_sets.py#L784-L815

**Comment by antoniojkim** [comment] 2022-12-12 15:25
I am unable to reproduce this with the latest `PyTorch` and latest `Torch-MLIR`. In my local testing:

Lazy tests:
```
Summary:
    Passed: 576
    Expectedly Failed: 170
```

Python tests:
```
Testing Time: 7.92s
  Passed: 17
```

**Comment by GlebKazantaev** [comment] 2023-01-06 15:50
The problem was related to the recent changes in torchgen types.
Fix: https://github.com/llvm/torch-mlir/pull/1779

**Comment by GlebKazantaev** [comment] 2023-01-06 22:04
PR https://github.com/llvm/torch-mlir/pull/1779 was merged. Closing.

**Closed by GlebKazantaev** 2023-01-06 22:04 UTC
Labels: regression
