### ISSUE TITLE
Implement Dynamic Case Support for View Expand/Collapse

### ISSUE THREAD

**Issue by JakopinA** [llvm/torch-mlir#1362] opened 2022-09-13 12:59 UTC
Hi there, I've been working on #1353 and have been having trouble figuring out how to implement support for Dynamic sizes, in particular [2, 3] -> [?, ?] -> [3, 2]. I've added support for static sizes with expand/collapse in this PR and it is already working, and I've been told the current function is modular enough to just slot in support for dynamic sizes. Would this be sufficient, or would I need to rewrite the whole matchAndRewrite function from scratch?

Here is an example of an E2E test I've made:
`
class ViewExpandDynamicDimModule(torch.nn.Module):
    def __init__(self):
        super().__init__()

    @export
    @annotate_args([
        None,
        ([1, -1, 128], torch.float32, True),
    ])

    def forward(self, a):
        return a.view(16, 1, 128)

@register_test_case(module_factory=lambda: ViewExpandDynamicDimModule())
def ViewExpandDynamicDimModule_basic(module, tu: TestUtils):
    module.forward(tu.rand(1, 16, 128))
`

This error currently fails at: `desired expand size is not compatible with the input tensor size`

@silvasean @ramiro050

**Comment by silvasean** [comment] 2022-09-13 19:02
The way I would phrase this is that "in the worst case, we just fully flatten and fully expand to the desired shape". So basically as a fallback after all the other parts don't match then we do that. It shouldn't be static shape specific.

**Comment by silvasean** [comment] 2022-09-13 19:59
Yes, the idea is that we analyze the tensor.size ops as well as we can, and then do the full flattening if we come up empty-handed.

**Comment by JakopinA** [comment] 2022-09-14 14:24
Gotcha. I'm just trying to figure out where exactly the border between "impossible to solve" and "possible to solve" is. Plus, as of now the view op is crashing instead of returning an error when doing [2,3] -> [?,?] -> [3,2], I'm sure that I need to make it so it returns an error instead of crashing.

**Comment by silvasean** [comment] 2022-10-07 13:06
Was this fixed by #1353? Is it a dupe of #1390 now?

**Comment by qedawkins** [comment] 2022-10-07 15:04
yes, it is now a dupe of #1390.

**Closed by qedawkins** 2022-10-07 15:04 UTC
