### ISSUE TITLE
Issue with trying to compile `DefaultAnchorGenerator` class from `detectron2` to `torch` dialect

### ISSUE THREAD

**Issue by LeeOHzzZ** [llvm/torch-mlir#950] opened 2022-06-16 21:25 UTC
Hi,

I have an issue trying to compile a pytorch program named `DefaultAnchorGenerator` from [detectron2](https://github.com/facebookresearch/detectron2/blob/224cd2318fdb45b5e22bbb861ee9711ee52c8b75/detectron2/modeling/anchor_generator.py#L86) to torch-mlir dialect.

The error message I got is as follows:
```mlir
<unknown>:0: error: 'torch.type_bound' must be attached to an argument of !torch.tensor/!torch.vtensor type
<unknown>:0: note: see current operation: "func.func"() ({
^bb0(%arg0: !torch.nn.Module<"__torch__.detectron2.modeling.anchor_generator.DefaultAnchorGenerator">, %arg1: !torch.list<tensor>):
  %0 = "torch.constant.none"() : () -> !torch.none
  %1 = "torch.constant.int"() {value = 1 : i64} : () -> !torch.int
  %2 = "torch.constant.int"() {value = -2 : i64} : () -> !torch.int
  %3 = "torch.constant.bool"() {value = true} : () -> !torch.bool
  %4 = "torch.prim.ListConstruct"() : () -> !torch.list<list<int>>
  %5 = "torch.aten.len.t"(%arg1) : (!torch.list<tensor>) -> !torch.int
  "torch.prim.Loop"(%5, %3) ({
  ^bb0(%arg2: !torch.int):
    %9 = "torch.aten.__getitem__.t"(%arg1, %arg2) : (!torch.list<tensor>, !torch.int) -> !torch.tensor
    %10 = "torch.aten.size"(%9) : (!torch.tensor) -> !torch.list<int>
    %11 = "torch.aten.slice.t"(%10, %2, %0, %1) : (!torch.list<int>, !torch.int, !torch.none, !torch.int) -> !torch.list<int>
    %12 = "torch.aten.append.t"(%4, %11) : (!torch.list<list<int>>, !torch.list<int>) -> !torch.list<list<int>>
    "torch.prim.Loop.condition"(%3) : (!torch.bool) -> ()
  }) : (!torch.int, !torch.bool) -> ()
  %6 = "torch.prim.CallMethod"(%arg0, %4) {name = "_grid_anchors"} : (!torch.nn.Module<"__torch__.detectron2.modeling.anchor_generator.DefaultAnchorGenerator">, !torch.list<list<int>>) -> !torch.list<tensor>
  %7 = "torch.prim.ListConstruct"() : () -> !torch.list<nn.Module<"__torch__.detectron2.structures.boxes.Boxes">>
  %8 = "torch.aten.len.t"(%6) : (!torch.list<tensor>) -> !torch.int
  "torch.prim.Loop"(%8, %3) ({
  ^bb0(%arg2: !torch.int):
    %9 = "torch.aten.__getitem__.t"(%6, %arg2) : (!torch.list<tensor>, !torch.int) -> !torch.tensor
    %10 = "torch.prim.CreateObject"() : () -> !torch.nn.Module<"__torch__.detectron2.structures.boxes.Boxes">
    %11 = "torch.prim.CallMethod"(%10, %9) {name = "__init__"} : (!torch.nn.Module<"__torch__.detectron2.structures.boxes.Boxes">, !torch.tensor) -> !torch.none
    %12 = "torch.aten.append.t"(%7, %10) : (!torch.list<nn.Module<"__torch__.detectron2.structures.boxes.Boxes">>, !torch.nn.Module<"__torch__.detectron2.structures.boxes.Boxes">) -> !torch.list<nn.Module<"__torch__.detectron2.structures.boxes.Boxes">>
    "torch.prim.Loop.condition"(%3) : (!torch.bool) -> ()
  }) : (!torch.int, !torch.bool) -> ()
  "func.return"(%7) : (!torch.list<nn.Module<"__torch__.detectron2.structures.boxes.Boxes">>) -> ()
}) {arg_attrs = [{}, {torch.type_bound = !torch.vtensor<[1,256,13,19],f32>}], function_type = (!torch.nn.Module<"__torch__.detectron2.modeling.anchor_generator.DefaultAnchorGenerator">, !torch.list<tensor>) -> !torch.list<nn.Module<"__torch__.detectron2.structures.boxes.Boxes">>, sym_name = "__torch__.detectron2.modeling.anchor_generator.DefaultAnchorGenerator.forward", sym_visibility = "private"} : () -> ()
```

Could somebody help me look into this issue? I've also put the python code to reproduce the error below:

```python
import torch
import torch_mlir
import detectron2

from detectron2.modeling.anchor_generator import DefaultAnchorGenerator

anchor_sizes = (32, 64, 96, 128, 160)
anchor_aspect_ratios = (0.5, 1.0, 2.0)
strides = [2]
offset = 0.5
feature_height = 13
feature_width = 19

anchor_gen = DefaultAnchorGenerator(
    sizes = anchor_sizes,
    aspect_ratios = anchor_aspect_ratios,
    strides = strides,
    offset = offset
)

example_tensor = torch.randn(
    [1, 256, feature_height, feature_width], dtype=torch.float32
)

# anchors = anchor_gen(example_tensor)[0]
# print(anchors)
# print(len(anchors))

compiled_torch = torch_mlir.compile(
    anchor_gen, example_tensor, torch_mlir.OutputType.LINALG_ON_TENSORS
)
print(compiled_torch)
```

Thank you!

**Comment by silvasean** [comment] 2022-10-10 11:45
I'm going to close this, since I think Torch-MLIR is working as intended -- we don't support lists of tensors as input.

**Closed by silvasean** 2022-10-10 11:45 UTC
